name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
      
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r21e
        add-to-path: true

    - name: Build 
      run: |
        set -euo pipefail
        build_mode="release"
        pushd zygisk/module
        rm -fr libs
        ndk-build -j4 NDK_DEBUG=0
        popd
        pushd java
        chmod +x ./gradlew
        ./gradlew assembleRelease
        popd
        mkdir -p magisk/zygisk
        for arch in arm64-v8a armeabi-v7a x86 x86_64
        do
            cp "zygisk/module/libs/$arch/libsafetynetfix.so" "magisk/zygisk/$arch.so"
        done
        pushd magisk
        version="$(grep '^version=' module.prop  | cut -d= -f2)"
        rm -f "../safetynet-fix-$version.zip" classes.dex
        unzip "../java/app/build/outputs/apk/release/app-release.apk" "classes.dex"
        zip -r9 "../safetynet-fix-$version.zip" .
        popd
        
    - name: Upload USNF release
      uses: actions/upload-artifact@v3
      with:
        name: "safetynet-fix.zip"
        path: "./safetynet-fix-$version.zip"
        
  
